### ISSUE TITLE
For release channel versions, put all point releases for each version on a single line

### ISSUE THREAD

**Issue by wsmwk** [thunderbird/thunderbird-website#808]
There tend to be very few point releases for each release channel version. It doesn't make a lot of sense to put these point release into columns or on separate lines.

I think also, it would be nice to add some distinguishing text next to the version number to indicate "ESR" or "Release".

**Comment by MelissaAutumn** [comment]
Yeah there should be a tab or filter to show esr/release versions. We talked about redoing this page for that, but haven't gotten around to it.

I'd hesitate against including all point releases on one line as ESR builds tend to have plenty of point releases. I think it's better to be consistent, but maybe that's something we can play around with if we split ESR/Release releases.

**Comment by Sancus** [comment]
I would like to tab this page by channel and add beta to it as well as release and ESR.

**Comment by wsmwk** [comment]
tabs def makes sense

**Comment by coreycb** [comment]
Just commenting to ensure it's known that 128 notes are missing from https://www.thunderbird.net/en-US/thunderbird/releases/
I thought I saw an issue for that in the past but I can't find it. A user just brought this up.

**Comment by janbrasna** [comment]
@coreycb It's resolved in https://github.com/thunderbird/thunderbird-website/issues/807 but the site just misses a prod push;) wink wink.

**Comment by EarlgreyPicard** [comment]
#807 has been closed, but the 128esr note remains missing at https://www.thunderbird.net/en-US/thunderbird/releases/.
According to the Internet Archive, 128esr has not been seen since the May 8th snapshot at the latest.
https://web.archive.org/web/20250508065327/https://www.thunderbird.net/en-US/thunderbird/releases/

Will things stay the way they are until each channels is made into tabs?
Is there any reason why the prod site is not updated?

**Comment by MelissaAutumn** [comment]
Also I should note: This issue is for a separate issue that isn't fixed 😅
